from game import Item
# items.py

class Item:
    def __init__(self, id, name, description, weight, armor_value, attack_value, durability, rarity, value, usable, stackable, effects=None, range=None, elemental_damage=None, required_level=0, quest_item=False):
        self.id = id
        self.name = name
        self.description = description
        self.weight = weight
        self.armor_value = armor_value
        self.attack_value = attack_value
        self.durability = durability
        self.rarity = rarity
        self.value = value
        self.usable = usable
        self.stackable = stackable
        self.effects = effects
        self.range = range
        self.elemental_damage = elemental_damage
        self.required_level = required_level
        self.quest_item = quest_item

item_type_translation = {
    "WEP": "Weapon",
    "KEY": "Key",
    "ARM": "Armor",
    "POT": "Potion",
    # Add more item type codes and translations as needed
}

item_dict = {
    "00000001": Item("00000001", "Healing Elixir", "A mystical elixir that restores health and mends wounds.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=10, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000002": Item("00000002", "Blade of Destiny", "Forged by ancient sorcery, this blade holds the fate of kingdoms.",
                     weight=5.0, armor_value=0, attack_value=50, durability=100, rarity="Legendary",
                     value=1000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=10, quest_item=False),
    "00000003": Item("00000003", "Shield of Guardians", "An enchanted shield that shields the bearer from dark forces.",
                     weight=10.0, armor_value=50, attack_value=0, durability=150, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=5, quest_item=False),
    "00000004": Item("00000004", "Ancient Map of Eldoria", "An ancient map that reveals the hidden realms of Eldoria.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=50, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000005": Item("00000005", "Key to Forbidden Citadel", "This key unlocks the gates of the forbidden Citadel.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=20, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=True),
    "00000006": Item("00000006", "Axe of Titan's Fury", "An immense battle axe imbued with the fury of ancient Titans.",
                     weight=8.0, armor_value=0, attack_value=75, durability=80, rarity="Rare",
                     value=800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "00000007": Item("00000007", "Mystic Chest of Enigma", "A mystical chest filled with enigmatic secrets and hidden knowledge.",
                     weight=20.0, armor_value=0, attack_value=0, durability=1, rarity="Legendary",
                     value=5000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000008": Item("00000008", "Orb of Divine Insight", "A radiant orb that grants profound wisdom and foresight.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=100, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000009": Item("00000009", "Amulet of Arcane Power", "An amulet that channels arcane energy to enhance the wearer's abilities.",
                     weight=0.2, armor_value=10, attack_value=0, durability=50, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=5, quest_item=False),
    "0000000A": Item("0000000A", "Ethereal Blaster", "A futuristic blaster that unleashes powerful ethereal energy bolts.",
                     weight=2.0, armor_value=0, attack_value=60, durability=60, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=6, quest_item=False),
    "0000000B": Item("0000000B", "Shadowstrike Blade", "A legendary blade that harnesses the darkness itself, capable of slicing through armor and vanquishing enemies with a single strike.",
                     weight=4.5, armor_value=0, attack_value=80, durability=120, rarity="Epic",
                     value=1500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=12, quest_item=False),
    "0000000C": Item("0000000C", "Crystalized Orb", "A mystic orb that emanates a brilliant light, capable of unlocking hidden powers and revealing the secrets of the arcane.",
                     weight=1.0, armor_value=0, attack_value=0, durability=50, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "0000000D": Item("0000000D", "Radiant Essence", "A shimmering essence infused with celestial energy, radiating with healing properties and restoring vitality to the wounded.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=20, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000000E": Item("0000000E", "Dragonheart Pendant", "A pendant crafted from the heart of a mighty dragon, granting the wearer impenetrable defense and the power to withstand even the fiercest of attacks.",
                     weight=0.8, armor_value=60, attack_value=0, durability=80, rarity="Legendary",
                     value=2000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=15, quest_item=False),
    "0000000F": Item("0000000F", "Tome of Arcane Knowledge", "A tome filled with ancient wisdom and forbidden spells, offering the key to unlocking the secrets of the arcane arts.",
                     weight=2.0, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000010": Item("00000010", "Celestial Longbow", "A bow infused with celestial energy, granting unparalleled accuracy and the ability to unleash devastating arrows imbued with divine power.",
                     weight=3.5, armor_value=0, attack_value=70, durability=150, rarity="Rare",
                     value=800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=10, quest_item=False),
    "00000011": Item("00000011", "Frostbite Gauntlets", "Gauntlets forged in the heart of an icy mountain, capable of freezing foes upon contact and providing resistance against frost-based attacks.",
                     weight=1.2, armor_value=40, attack_value=0, durability=100, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "00000012": Item("00000012", "Thundering Warhammer", "A massive warhammer infused with the power of thunder, generating thunderstorms with each mighty swing and striking fear into the hearts of enemies.",
                     weight=6.0, armor_value=0, attack_value=90, durability=120, rarity="Epic",
                     value=1800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=14, quest_item=False),
    "00000013": Item("00000013", "Luminous Elixir", "An elixir concocted from rare glowing herbs, radiating a soothing aura that restores health and grants temporary resistance to dark magic.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=50, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000014": Item("00000014", "Enchanted Robes", "Robes woven with ancient enchantments, providing exceptional magical protection and enhancing the wearer's spellcasting abilities.",
                     weight=2.5, armor_value=50, attack_value=0, durability=80, rarity="Rare",
                     value=700, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=10, quest_item=False),
    "00000015": Item("00000015", "Viper's Fang Dagger", "A deadly dagger crafted from the fang of a venomous serpent, delivering swift and precise strikes that inflict deadly poison upon enemies.",
                     weight=0.8, armor_value=0, attack_value=60, durability=100, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "00000016": Item("00000016", "Golem Core Shard", "A shard imbued with the essence of a mighty golem, granting the bearer increased strength and the ability to withstand tremendous physical force.",
                     weight=1.5, armor_value=20, attack_value=0, durability=80, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=5, quest_item=False),
    "00000017": Item("00000017", "Phoenix Feather Quill", "A quill plucked from the majestic wings of a phoenix, enabling the writing of powerful spells and granting the ability to unleash fiery magic.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=80, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000018": Item("00000018", "Stormguard Shield", "A shield infused with the power of thunderstorms, creating a protective barrier that absorbs and redirects lightning-based attacks.",
                     weight=4.0, armor_value=70, attack_value=0, durability=150, rarity="Rare",
                     value=900, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=12, quest_item=False),
    "00000019": Item("00000019", "Whisperwind Boots", "Boots crafted from the ethereal essence of the Whisperwind, granting the wearer increased speed and the ability to move in silence.",
                     weight=1.2, armor_value=30, attack_value=0, durability=100, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "0000001A": Item("0000001A", "Silvermoon Amulet", "An amulet blessed by the moonlight of the Silvermoon, enhancing the bearer's magical prowess and granting the ability to harness moon-based spells.",
                     weight=0.4, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000001B": Item("0000001B", "Venomous Vial", "A vial filled with potent venom extracted from deadly creatures, capable of poisoning enemies and causing debilitating effects.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=30, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000001C": Item("0000001C", "Astral Compass", "A compass infused with astral energy, guiding the bearer through uncharted realms and revealing hidden paths to distant lands.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000001D": Item("0000001D", "Runebound Armor", "Armor adorned with ancient runes, providing mystical protection and increasing the wearer's resistance against magical attacks.",
                     weight=5.0, armor_value=80, attack_value=0, durability=120, rarity="Epic",
                     value=2000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=15, quest_item=False),
    "0000001E": Item("0000001E", "Glimmering Pearl", "A radiant pearl imbued with shimmering magic, granting the ability to illuminate darkness and revealing hidden treasures.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=40, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000001F": Item("0000001F", "Flameforged Greatsword", "A greatsword forged in the heart of an ancient volcano, engulfed in everlasting flames and capable of cleaving through any obstacle.",
                     weight=7.0, armor_value=0, attack_value=100, durability=150, rarity="Epic",
                     value=2200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=16, quest_item=False),
    "00000020": Item("00000020", "Dreamweaver Staff", "A staff woven with the essence of dreams, allowing the bearer to delve into the realm of dreams and harness its power to shape reality.",
                     weight=4.5, armor_value=0, attack_value=60, durability=120, rarity="Rare",
                     value=700, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=12, quest_item=False),
    "00000021": Item("00000021", "Serpent's Scale Mail", "Armor crafted from the scales of a mighty serpent, providing exceptional protection against poison and granting resistance to venomous attacks.",
                     weight=6.5, armor_value=90, attack_value=0, durability=150, rarity="Epic",
                     value=2500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=18, quest_item=False),
    "00000022": Item("00000022", "Starlight Cloak", "A cloak infused with the power of the stars, granting the wearer enhanced agility and the ability to blend with the night sky, rendering them invisible.",
                     weight=2.0, armor_value=30, attack_value=0, durability=100, rarity="Rare",
                     value=800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=10, quest_item=False),
    "00000023": Item("00000023", "Ancient Relic", "A relic from a bygone era, radiating ancient magic and holding the key to unlocking forgotten knowledge and secrets of the past.",
                     weight=3.0, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000024": Item("00000024", "Swiftwind Boots", "Boots imbued with the swiftness of the wind, granting the wearer increased speed and agility, allowing them to move with unparalleled grace.",
                     weight=1.0, armor_value=20, attack_value=0, durability=80, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=5, quest_item=False),
    "00000025": Item("00000025", "Cursed Skull Pendant", "A pendant cursed by dark sorcery, granting the bearer increased power but at a terrible cost, consuming their life essence over time.",
                     weight=0.6, armor_value=10, attack_value=0, durability=50, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "00000026": Item("00000026", "Thunderstrike Gauntlets", "Gauntlets infused with the power of thunderstorms, allowing the wearer to summon lightning bolts and unleash devastating electrical attacks.",
                     weight=1.5, armor_value=40, attack_value=0, durability=100, rarity="Rare",
                     value=700, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "00000027": Item("00000027", "Frostbite Arrows", "Arrows crafted from enchanted ice, capable of freezing enemies upon impact and leaving them vulnerable to subsequent attacks.",
                     weight=0.1, armor_value=0, attack_value=40, durability=100, rarity="Uncommon",
                     value=50, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=5, quest_item=False),
    "00000028": Item("00000028", "Essence of Eternal Flame", "A vial containing the essence of an eternal flame, granting the ability to unleash devastating fire-based attacks and ignite surroundings.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=30, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000031": Item("00000031", "Wooden Shovel", "A basic wooden shovel, suitable for digging small holes and trenches.",
                     weight=2.0, armor_value=0, attack_value=5, durability=50, rarity="Common",
                     value=15, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000032": Item("00000032", "Iron Spade", "An iron spade with a sturdy handle, designed for digging in tough and rocky terrains.",
                     weight=3.5, armor_value=0, attack_value=8, durability=75, rarity="Common",
                     value=25, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000033": Item("00000033", "Oil Lantern", "A traditional oil-powered lantern that provides a steady source of light in dark environments.",
                     weight=1.5, armor_value=0, attack_value=0, durability=30, rarity="Common",
                     value=10, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000034": Item("00000034", "Iron Key", "A simple iron key that can unlock various standard locks.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=5, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000035": Item("00000035", "Leather Gloves", "A pair of simple leather gloves, providing basic protection for the hands.",
                     weight=0.3, armor_value=5, attack_value=0, durability=20, rarity="Common",
                     value=8, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000036": Item("00000036", "Iron Keyring", "A keyring made of iron, capable of holding multiple keys.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=3, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000037": Item("00000037", "Leather Pouch", "A small leather pouch, useful for storing coins, gems, and other small items.",
                     weight=0.5, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=5, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000038": Item("00000038", "Rope", "A sturdy rope made of natural fibers, suitable for various utility purposes.",
                     weight=1.0, armor_value=0, attack_value=0, durability=50, rarity="Common",
                     value=10, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000039": Item("00000039", "Cooking Pot", "A medium-sized cooking pot made of cast iron, perfect for preparing meals during outdoor adventures.",
                     weight=2.5, armor_value=0, attack_value=0, durability=40, rarity="Common",
                     value=15, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000003A": Item("0000003A", "Ink Bottle", "A small glass bottle filled with ink, commonly used for writing and drawing.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=5, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000003B": Item("0000003B", "Chalk", "A piece of chalk made from compressed calcium carbonate, often used for writing on blackboards or marking paths.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=2, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000003C": Item("0000003C", "Glass Bottle", "A transparent glass bottle with a cork stopper, suitable for holding liquids or small items.",
                     weight=0.4, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=5, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000003D": Item("0000003D", "Wooden Bowl", "A simple wooden bowl, useful for holding food or other small items.",
                     weight=0.3, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=3, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000003E": Item("0000003E", "Fishing Net", "A sturdy net made of woven fibers, designed for catching fish or other aquatic creatures.",
                     weight=1.2, armor_value=0, attack_value=0, durability=30, rarity="Common",
                     value=12, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000003F": Item("0000003F", "Iron Buckle", "A sturdy iron buckle commonly used for fastening belts or straps.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=2, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000040": Item("00000040", "Leather Belt", "A simple leather belt with a metal buckle, used to hold clothing or secure equipment.",
                     weight=0.4, armor_value=2, attack_value=0, durability=15, rarity="Common",
                     value=6, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000041": Item("00000041", "Wooden Mug", "A sturdy wooden mug, suitable for holding and drinking beverages.",
                     weight=0.3, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=3, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000042": Item("00000042", "Flint and Steel", "A set consisting of a small piece of flint and a metal striker, used to create sparks and start fires.",
                     weight=0.2, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=7, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000043": Item("00000043", "Wooden Spoon", "A basic wooden spoon, useful for stirring and mixing ingredients while cooking.",
                     weight=0.3, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=2, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000044": Item("00000044", "Traveler's Journal", "A compact journal with blank pages, intended for recording travel experiences and observations.",
                     weight=0.6, armor_value=0, attack_value=0, durability=15, rarity="Common",
                     value=8, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000045": Item("00000045", "Cloth Bandage", "A soft cloth bandage used to wrap wounds and provide basic medical care.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=3, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000046": Item("00000046", "Iron Nails", "A small bundle of iron nails, commonly used for construction or repairing items.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=4, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000047": Item("00000047", "Wooden Comb", "A simple wooden comb, used for grooming and styling hair.",
                     weight=0.2, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=2, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000048": Item("00000048", "Fishing Hook", "A sharp fishing hook attached to a line, used for catching fish.",
                     weight=0.1, armor_value=0, attack_value=2, durability=1, rarity="Common",
                     value=2, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000049": Item("00000049", "Enchanted Cloak", "A magical cloak that provides protection against the elements.",
                     weight=2.0, armor_value=10, attack_value=0, durability=50, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=5, quest_item=False),
    "0000004A": Item("0000004A", "Satchel of Holding", "A satchel enchanted with a dimensional pocket, allowing for increased storage capacity.",
                     weight=1.5, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000004B": Item("0000004B", "Glowstone Pendant", "A pendant infused with magical energy, emitting a soft glow in dark environments.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000004C": Item("0000004C", "Smoke Bomb", "A small explosive device that creates a dense cloud of smoke, useful for stealth and distraction.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=100, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000004D": Item("0000004D", "Mystic Rune", "An ancient rune inscribed on a small stone tablet, believed to hold mystical powers.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=200, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000004E": Item("0000004E", "Pocket Watch", "A finely crafted pocket watch, allowing for accurate timekeeping.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000004F": Item("0000004F", "Elven Tonic", "A special elven brew that provides temporary enhancements to agility and reflexes.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=250, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000050": Item("00000050", "Ancient Relic", "A mysterious artifact from a long-lost civilization, holding untold secrets.",
                     weight=5.0, armor_value=0, attack_value=0, durability=1, rarity="Rare",
                     value=1000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000051": Item("00000051", "Crystal Staff", "A staff carved from a rare crystal, amplifying magical abilities.",
                     weight=4.0, armor_value=0, attack_value=50, durability=80, rarity="Rare",
                     value=800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "00000052": Item("00000052", "Dwarven Ale", "A strong and flavorful ale brewed by skilled dwarven craftsmen.",
                     weight=0.8, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=80, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000053": Item("00000053", "Lucky Charm", "A small charm believed to bring good fortune and increase luck.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=100, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000054": Item("00000054", "Ranger's Quiver", "A specially designed quiver that increases arrow capacity and quickens reloading.",
                     weight=1.5, armor_value=0, attack_value=0, durability=40, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000055": Item("00000055", "Silk Gloves", "Elegant gloves made from fine silk, providing dexterity and comfort.",
                     weight=0.2, armor_value=5, attack_value=0, durability=20, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000056": Item("00000056", "Harmonious Flute", "A beautifully crafted wooden flute, capable of producing enchanting melodies.",
                     weight=0.4, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=180, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000057": Item("00000057", "Poisoned Dagger", "A small dagger coated with a deadly poison, inflicting additional damage over time.",
                     weight=0.8, armor_value=0, attack_value=30, durability=30, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000058": Item("00000058", "Thieves' Tools", "A set of tools commonly used by skilled thieves for lockpicking and stealthy activities.",
                     weight=0.5, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=180, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000059": Item("00000059", "Wanderer's Boots", "Sturdy leather boots designed for long journeys, providing comfort and endurance.",
                     weight=1.2, armor_value=10, attack_value=0, durability=40, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000005A": Item("0000005A", "Soulstone", "A small crystal imbued with ancient magic, capable of storing the essence of fallen creatures.",
                     weight=0.3, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000005B": Item("0000005B", "Hunter's Bow", "A well-crafted bow favored by hunters, providing increased accuracy and range.",
                     weight=2.0, armor_value=0, attack_value=40, durability=60, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000005C": Item("0000005C", "Potion of Invisibility", "A magical potion that grants temporary invisibility to the drinker.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=200, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000005D": Item("0000005D", "Elven Bow", "An elegant bow crafted by skilled elven archers, granting increased precision and power.",
                     weight=1.8, armor_value=0, attack_value=45, durability=70, rarity="Rare",
                     value=700, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=7, quest_item=False),
    "0000005E": Item("0000005E", "Wand of Fireballs", "A wand infused with fire magic, allowing the wielder to unleash powerful fireballs.",
                     weight=0.8, armor_value=0, attack_value=55, durability=60, rarity="Rare",
                     value=800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=8, quest_item=False),
    "0000005F": Item("0000005F", "Elixir of Strength", "A potent elixir that temporarily enhances the drinker's physical strength.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=200, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000060": Item("00000060", "Enchanted Necklace", "A necklace adorned with enchanted gemstones, bestowing magical protection.",
                     weight=0.6, armor_value=15, attack_value=0, durability=40, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000061": Item("00000061", "Bard's Lute", "A musical instrument favored by bards, capable of enchanting listeners with its melodies.",
                     weight=1.2, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=180, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000062": Item("00000062", "Cloak of Shadows", "A dark cloak that grants the wearer enhanced stealth and evasion abilities.",
                     weight=1.5, armor_value=20, attack_value=0, durability=50, rarity="Rare",
                     value=800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000063": Item("00000063", "Scroll of Teleportation", "A magical scroll that instantly transports the reader to a previously marked location.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000064": Item("00000064", "Silk Robes", "Exquisite robes made from fine silk, providing magical affinity and comfort.",
                     weight=2.0, armor_value=15, attack_value=0, durability=30, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000065": Item("00000065", "Book of Enchantments", "A thick book containing ancient knowledge of enchantments and magical rituals.",
                     weight=1.8, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000066": Item("00000066", "Trap Kit", "A set of tools used for setting up traps and mechanisms to deter intruders.",
                     weight=1.2, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=180, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000067": Item("00000067", "Enchanted Bracelet", "A bracelet infused with magical energies, enhancing the wearer's spellcasting abilities.",
                     weight=0.4, armor_value=10, attack_value=0, durability=40, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000068": Item("00000068", "Phoenix Feather", "A feather from a mythical phoenix, said to possess regenerative properties.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000069": Item("00000069", "Crystal Shard", "A shard of rare crystal with various magical properties.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=100, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000006A": Item("0000006A", "Sneak's Dagger", "A small, lightweight dagger favored by stealthy assassins.",
                     weight=0.6, armor_value=0, attack_value=25, durability=40, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000006B": Item("0000006B", "Sorcerer's Hat", "A pointed hat worn by sorcerers and wizards, enhancing magical potency.",
                     weight=0.3, armor_value=5, attack_value=0, durability=30, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000006C": Item("0000006C", "Sleeping Bag", "A portable and comfortable sleeping bag for resting during long journeys.",
                     weight=1.0, armor_value=0, attack_value=0, durability=1, rarity="Common",
                     value=50, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000006D": Item("0000006D", "Elixir of Clarity", "A magical elixir that clears the mind and enhances focus and concentration.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=200, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000006E": Item("0000006E", "Explorer's Hat", "A wide-brimmed hat favored by adventurers and explorers, providing protection from the sun and rain.",
                     weight=0.4, armor_value=5, attack_value=0, durability=30, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000006F": Item("0000006F", "Book of Shadows", "A tome containing dark and forbidden knowledge, granting access to powerful dark magic spells.",
                     weight=1.5, armor_value=0, attack_value=0, durability=1, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000070": Item("00000070", "Horn of Summoning", "A magical horn used to summon and communicate with mystical creatures.",
                     weight=0.8, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=180, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000071": Item("00000071", "Spider Silk Gloves", "Gloves made from the silk of giant spiders, providing increased dexterity and resistance to web-based attacks.",
                     weight=0.3, armor_value=10, attack_value=0, durability=40, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000072": Item("00000072", "Gem of Power", "A precious gem imbued with raw magical energy, used for various enchantments and rituals.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000073": Item("00000073", "Blessed Water", "Water that has been blessed by divine entities, capable of healing wounds and curing ailments.",
                     weight=0.8, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=200, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000074": Item("00000074", "Moonstone Ring", "A ring adorned with a moonstone, enhancing the wearer's magical abilities during nighttime.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000075": Item("00000075", "Crystal Orb", "A crystal orb used by seers and fortune-tellers to glimpse into the future.",
                     weight=0.5, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000076": Item("00000076", "Warding Talisman", "A talisman inscribed with protective runes, providing enhanced defense against magical attacks.",
                     weight=0.2, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000077": Item("00000077", "Bandit Mask", "A mask worn by bandits and rogues to conceal their identity and intimidate their victims.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000078": Item("00000078", "Skull Lantern", "A lantern made from a human skull, emitting an eerie glow that repels undead creatures.",
                     weight=1.0, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=180, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000079": Item("00000079", "Mystic Feather", "A feather infused with magical energies, capable of redirecting projectiles and providing limited levitation.",
                     weight=0.1, armor_value=0, attack_value=0, durability=1, rarity="Uncommon",
                     value=120, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000007A": Item("0000007A", "Enchanted Mirror", "A mystical mirror that reveals hidden truths and reflects the soul.",
                     weight=1.5, armor_value=0, attack_value=0, durability=40, rarity="Rare",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000007B": Item("0000007B", "Soulstone Pendant", "A pendant containing a captured soul, which grants the wearer increased vitality.",
                     weight=0.3, armor_value=2, attack_value=0, durability=30, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000007C": Item("0000007C", "Whispering Dagger", "A dagger forged by ancient assassins, rumored to whisper secrets to its wielder.",
                     weight=0.8, armor_value=0, attack_value=30, durability=60, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000007D": Item("0000007D", "Elven Bow", "A finely crafted bow of elven design, known for its accuracy and long range.",
                     weight=2.5, armor_value=0, attack_value=40, durability=70, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000007E": Item("0000007E", "Scroll of Knowledge", "A scroll containing ancient wisdom and knowledge, granting insights to its reader.",
                     weight=0.2, armor_value=0, attack_value=0, durability=20, rarity="Common",
                     value=50, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000007F": Item("0000007F", "Ring of Protection", "A ring imbued with protective enchantments, increasing the wearer's defense.",
                     weight=0.1, armor_value=3, attack_value=0, durability=10, rarity="Uncommon",
                     value=80, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000080": Item("00000080", "Dragon Scale Armor", "Armor crafted from the scales of a mighty dragon, providing exceptional protection.",
                     weight=8.0, armor_value=70, attack_value=0, durability=120, rarity="Legendary",
                     value=5000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000081": Item("00000081", "Invisibility Cloak", "A cloak that grants the ability to become invisible, allowing the wearer to sneak undetected.",
                     weight=1.2, armor_value=8, attack_value=0, durability=80, rarity="Rare",
                     value=800, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000082": Item("00000082", "Frost Shard", "A shard of ice imbued with the power of frost, capable of freezing enemies on contact.",
                     weight=0.4, armor_value=0, attack_value=20, durability=50, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Frost", required_level=0, quest_item=False),
    "00000083": Item("00000083", "Wand of Fireballs", "A wand that unleashes powerful fireballs, engulfing enemies in flames.",
                     weight=0.6, armor_value=0, attack_value=25, durability=40, rarity="Rare",
                     value=350, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Fire", required_level=0, quest_item=False),
    "00000084": Item("00000084", "Book of Shadows", "A forbidden tome containing dark and arcane knowledge, empowering the reader with forbidden spells.",
                     weight=1.0, armor_value=0, attack_value=0, durability=60, rarity="Legendary",
                     value=5000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000085": Item("00000085", "Amulet of the Moon", "An amulet infused with lunar magic, enhancing the wearer's mystical abilities during the night.",
                     weight=0.2, armor_value=1, attack_value=0, durability=30, rarity="Rare",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000086": Item("00000086", "Hunter's Crossbow", "A crossbow favored by skilled hunters, designed for precision and ease of use.",
                     weight=3.0, armor_value=0, attack_value=45, durability=70, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000087": Item("00000087", "Druidic Staff", "A staff infused with the power of nature, allowing the wielder to channel the elements.",
                     weight=2.5, armor_value=0, attack_value=35, durability=60, rarity="Uncommon",
                     value=180, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000088": Item("00000088", "Shadow Cloak", "A cloak woven from shadowy fabric, granting the wearer enhanced stealth and agility.",
                     weight=1.2, armor_value=6, attack_value=0, durability=60, rarity="Rare",
                     value=450, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000089": Item("00000089", "Elixir of Agility", "An elixir that enhances the user's speed and reflexes, granting increased agility.",
                     weight=0.3, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=120, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000008A": Item("0000008A", "Enchanted Gloves", "Gloves infused with enchantments, increasing the wearer's dexterity and magical prowess.",
                     weight=0.5, armor_value=2, attack_value=0, durability=40, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000008B": Item("0000008B", "Holy Relic", "A sacred relic imbued with divine energy, capable of repelling dark forces.",
                     weight=0.8, armor_value=0, attack_value=0, durability=50, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000008C": Item("0000008C", "Sonic Boom Boots", "Boots that harness the power of sound, allowing the wearer to unleash devastating shockwaves.",
                     weight=1.5, armor_value=3, attack_value=0, durability=60, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000008D": Item("0000008D", "Venomous Blade", "A blade coated with deadly venom, causing additional poison damage to enemies.",
                     weight=1.0, armor_value=0, attack_value=40, durability=70, rarity="Uncommon",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Poison", required_level=0, quest_item=False),
    "0000008E": Item("0000008E", "Glowing Crystal", "A crystal that emits a soft, enchanting glow, providing illumination in the darkest of places.",
                     weight=0.2, armor_value=0, attack_value=0, durability=20, rarity="Common",
                     value=50, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000008F": Item("0000008F", "Enchanted Bowtie", "A stylish bowtie enchanted with magic, granting the wearer a touch of elegance and charm.",
                     weight=0.1, armor_value=1, attack_value=0, durability=20, rarity="Uncommon",
                     value=80, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000090": Item("00000090", "Oracle's Staff", "A staff infused with the power of foresight, enabling the wielder to see into the future.",
                     weight=2.0, armor_value=0, attack_value=30, durability=60, rarity="Rare",
                     value=350, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000091": Item("00000091", "Gauntlets of Strength", "Gauntlets imbued with ancient strength-enhancing enchantments, granting incredible power.",
                     weight=1.5, armor_value=5, attack_value=0, durability=70, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000092": Item("00000092", "Mysterious Elixir", "A mysterious elixir with unknown properties, rumored to bestow temporary magical abilities.",
                     weight=0.4, armor_value=0, attack_value=0, durability=30, rarity="Rare",
                     value=400, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000093": Item("00000093", "Shield of Reflection", "A shield that reflects incoming projectiles and spells, providing enhanced defense.",
                     weight=4.0, armor_value=60, attack_value=0, durability=90, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000094": Item("00000094", "Moonstone Necklace", "A necklace adorned with a shimmering moonstone, granting heightened magical abilities under moonlight.",
                     weight=0.2, armor_value=0, attack_value=0, durability=20, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000095": Item("00000095", "Cross Pendant", "A pendant bearing the symbol of faith, providing protection against undead creatures.",
                     weight=0.3, armor_value=2, attack_value=0, durability=30, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000096": Item("00000096", "Thunderstorm Tome", "A powerful tome that conjures a raging thunderstorm, striking down enemies with lightning bolts.",
                     weight=1.0, armor_value=0, attack_value=0, durability=60, rarity="Legendary",
                     value=5000, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Lightning", required_level=0, quest_item=False),
    "00000097": Item("00000097", "Assassin's Hood", "A hood favored by assassins, providing increased stealth and critical strike chance.",
                     weight=0.8, armor_value=4, attack_value=0, durability=50, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000098": Item("00000098", "Crimson Orchid", "A rare orchid with crimson petals, possessing healing properties when consumed.",
                     weight=0.1, armor_value=0, attack_value=0, durability=10, rarity="Uncommon",
                     value=80, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "00000099": Item("00000099", "Enchanted Harp", "A harp enchanted with magical melodies, capable of soothing hearts and calming minds.",
                     weight=2.0, armor_value=0, attack_value=25, durability=60, rarity="Rare",
                     value=350, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000009A": Item("0000009A", "Glimmering Dagger", "A dagger that glimmers with ethereal light, striking fear into the hearts of enemies.",
                     weight=0.6, armor_value=0, attack_value=35, durability=70, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000009B": Item("0000009B", "Crystal Shield", "A shield crafted from enchanted crystals, providing excellent magical defense.",
                     weight=5.0, armor_value=50, attack_value=0, durability=100, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000009C": Item("0000009C", "Stealthy Boots", "Boots designed for silent movement, allowing the wearer to move undetected in the shadows.",
                     weight=1.2, armor_value=3, attack_value=0, durability=60, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000009D": Item("0000009D", "Scepter of Light", "A powerful scepter emanating a radiant light, capable of banishing darkness and dispelling evil.",
                     weight=1.8, armor_value=0, attack_value=40, durability=70, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000009E": Item("0000009E", "Ancient Scroll", "An ancient scroll inscribed with forgotten knowledge, containing powerful incantations.",
                     weight=0.3, armor_value=0, attack_value=0, durability=20, rarity="Common",
                     value=50, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "0000009F": Item("0000009F", "Enchanted Necklace", "A necklace adorned with enchantments, enhancing the wearer's magical abilities.",
                     weight=0.2, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A0": Item("000000A0", "Vampiric Blade", "A blade that drains the life force of enemies, granting health to the wielder with each strike.",
                     weight=1.2, armor_value=0, attack_value=45, durability=70, rarity="Uncommon",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A1": Item("000000A1", "Arcane Runestone", "A runestone inscribed with arcane symbols, empowering spells and increasing magical potency.",
                     weight=0.5, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A2": Item("000000A2", "Feathered Hat", "A hat adorned with colorful feathers, bestowing a touch of elegance and style.",
                     weight=0.3, armor_value=1, attack_value=0, durability=30, rarity="Uncommon",
                     value=80, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A3": Item("000000A3", "Harmony Medallion", "A medallion that radiates harmony, providing increased resistance against disruptive magic.",
                     weight=0.2, armor_value=2, attack_value=0, durability=20, rarity="Rare",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A4": Item("000000A4", "Singing Sword", "A sword that sings with a melodic hum, resonating with the wielder's battle prowess.",
                     weight=2.5, armor_value=0, attack_value=50, durability=80, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A5": Item("000000A5", "Gem of Enlightenment", "A gem infused with ancient wisdom, granting profound insights and increased intellect.",
                     weight=0.1, armor_value=0, attack_value=0, durability=10, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A6": Item("000000A6", "Enchanted Boots", "Boots enchanted with magical swiftness, enhancing the wearer's speed and mobility.",
                     weight=1.0, armor_value=2, attack_value=0, durability=40, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A7": Item("000000A7", "Nightshade Dagger", "A dagger infused with the essence of shadows, granting increased critical strike chance under the cover of darkness.",
                     weight=0.8, armor_value=0, attack_value=35, durability=60, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A8": Item("000000A8", "Spellbound Grimoire", "A grimoire filled with enchantments and magical formulas, enabling the casting of advanced spells.",
                     weight=1.5, armor_value=0, attack_value=0, durability=50, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000A9": Item("000000A9", "Phoenix Feather", "A feather from a mythical phoenix, radiating intense heat and capable of igniting fires.",
                     weight=0.1, armor_value=0, attack_value=0, durability=10, rarity="Uncommon",
                     value=80, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage="Fire", required_level=0, quest_item=False),
    "000000AA": Item("000000AA", "Crystalized Bow", "A bow crafted from crystalized energy, shooting arrows infused with magical power.",
                     weight=2.5, armor_value=0, attack_value=45, durability=70, rarity="Uncommon",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000AB": Item("000000AB", "Glowing Lantern", "A lantern that emits a gentle, soothing glow, illuminating the surroundings.",
                     weight=1.0, armor_value=0, attack_value=0, durability=60, rarity="Common",
                     value=50, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000AC": Item("000000AC", "Crystal Blade", "A blade crafted from enchanted crystals, capable of channeling magical energy for devastating attacks.",
                     weight=1.8, armor_value=0, attack_value=40, durability=70, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000AD": Item("000000AD", "Oracle's Robe", "A robe worn by seers and prophets, empowering the wearer with heightened magical perception.",
                     weight=2.0, armor_value=10, attack_value=0, durability=80, rarity="Rare",
                     value=450, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000AE": Item("000000AE", "Soulbound Necklace", "A necklace imbued with the essence of a powerful soul, providing protection against dark forces.",
                     weight=0.3, armor_value=3, attack_value=0, durability=30, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000AF": Item("000000AF", "Thunderstrike Hammer", "A mighty hammer capable of summoning thunderstorms and unleashing powerful lightning strikes.",
                     weight=8.0, armor_value=0, attack_value=55, durability=90, rarity="Rare",
                     value=600, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Lightning", required_level=0, quest_item=False),
    "000000B0": Item("000000B0", "Enchanted Quiver", "A quiver enchanted with magical properties, providing an endless supply of arrows.",
                     weight=1.5, armor_value=0, attack_value=0, durability=50, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B1": Item("000000B1", "Scroll of Teleportation", "A scroll that allows the user to instantly teleport to a known location.",
                     weight=0.2, armor_value=0, attack_value=0, durability=20, rarity="Uncommon",
                     value=120, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B2": Item("000000B2", "Golem's Heartstone", "A heart-shaped stone extracted from a defeated golem, radiating with residual magical energy.",
                     weight=0.5, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B3": Item("000000B3", "Silent Boots", "Boots designed for stealthy movement, muffling footsteps and suppressing sound.",
                     weight=1.2, armor_value=4, attack_value=0, durability=60, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B4": Item("000000B4", "Fiery Essence", "A vial containing a potent essence of fire, capable of enhancing fire-based spells and attacks.",
                     weight=0.3, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=120, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage="Fire", required_level=0, quest_item=False),
    "000000B5": Item("000000B5", "Enchanted Cuffs", "Cuffs adorned with enchantments, granting the wearer increased resistance to magic.",
                     weight=0.4, armor_value=2, attack_value=0, durability=40, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B6": Item("000000B6", "Mystic Cloak", "A cloak woven with intricate mystical patterns, enhancing the wearer's magical abilities.",
                     weight=1.5, armor_value=6, attack_value=0, durability=70, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B7": Item("000000B7", "Sapphire Pendant", "A pendant adorned with a sparkling sapphire, enhancing the wearer's magical aptitude.",
                     weight=0.2, armor_value=1, attack_value=0, durability=30, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B8": Item("000000B8", "Spiritbound Bow", "A bow infused with the essence of ethereal spirits, granting increased accuracy and critical strike chance.",
                     weight=2.5, armor_value=0, attack_value=40, durability=70, rarity="Uncommon",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000B9": Item("000000B9", "Cursed Talisman", "A talisman imbued with a dark curse, amplifying the wearer's dark magic but at a cost.",
                     weight=0.3, armor_value=0, attack_value=0, durability=30, rarity="Rare",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000BA": Item("000000BA", "Glowing Mushroom", "A luminescent mushroom that emits a soft glow, providing light in dark places.",
                     weight=0.1, armor_value=0, attack_value=0, durability=10, rarity="Uncommon",
                     value=80, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000BB": Item("000000BB", "Enchanted Mirror", "A mirror enchanted with a spell of reflection, capable of reflecting magical attacks.",
                     weight=1.5, armor_value=0, attack_value=0, durability=40, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000BC": Item("000000BC", "Helm of the Berserker", "A helm infused with the spirit of a raging berserker, enhancing the wearer's strength and ferocity in battle.",
                     weight=2.0, armor_value=8, attack_value=0, durability=80, rarity="Rare",
                     value=500, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000BD": Item("000000BD", "Crystal of Resilience", "A crystal that fortifies the wearer's resilience, reducing the duration of negative status effects.",
                     weight=0.2, armor_value=2, attack_value=0, durability=20, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000BE": Item("000000BE", "Nightshade Elixir", "An elixir brewed from rare nightshade plants, providing temporary heightened senses and perception.",
                     weight=0.3, armor_value=0, attack_value=0, durability=30, rarity="Uncommon",
                     value=120, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000BF": Item("000000BF", "Mystic Amulet", "An amulet infused with ancient mystical energies, amplifying the wearer's magical abilities.",
                     weight=0.1, armor_value=1, attack_value=0, durability=20, rarity="Uncommon",
                     value=80, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C0": Item("000000C0", "Enchanted Gloves", "Gloves imbued with enchantments, granting the wearer increased dexterity and magical finesse.",
                     weight=0.5, armor_value=2, attack_value=0, durability=40, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C1": Item("000000C1", "Silent Shiv", "A small, deadly Shiv that makes no sound when wielded, perfect for stealthy assassinations.",
                     weight=0.3, armor_value=0, attack_value=25, durability=50, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C2": Item("000000C2", "Wand of Frost", "A wand that unleashes icy blasts, freezing enemies and slowing their movements.",
                     weight=0.4, armor_value=0, attack_value=30, durability=40, rarity="Rare",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Frost", required_level=0, quest_item=False),
    "000000C3": Item("000000C3", "Ethereal Robe", "A robe crafted from ethereal fabric, enhancing the wearer's magical abilities and providing ethereal protection.",
                     weight=1.5, armor_value=6, attack_value=0, durability=70, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C4": Item("000000C4", "Vampiric Amulet", "An amulet that feeds on the life force of enemies, granting health to the wearer with each successful attack.",
                     weight=0.2, armor_value=1, attack_value=0, durability=30, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C5": Item("000000C5", "Flaming Sword", "A sword imbued with the essence of fire, engulfing enemies in flames upon striking.",
                     weight=2.0, armor_value=0, attack_value=35, durability=60, rarity="Rare",
                     value=450, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Fire", required_level=0, quest_item=False),
    "000000C6": Item("000000C6", "Glyphed Dagger", "A dagger inscribed with ancient glyphs, increasing critical strike chance and amplifying magical damage.",
                     weight=0.6, armor_value=0, attack_value=30, durability=50, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C7": Item("000000C7", "Crystal Staff", "A staff crafted from enchanted crystals, channeling the power of arcane energy with great precision.",
                     weight=2.5, armor_value=0, attack_value=40, durability=70, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C8": Item("000000C8", "Soulstone Ring", "A ring containing a captured soul, providing enhanced magical abilities to the wearer.",
                     weight=0.1, armor_value=2, attack_value=0, durability=20, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000C9": Item("000000C9", "Nature's Embrace", "A charm infused with the essence of nature, granting the wearer increased vitality and affinity with flora and fauna.",
                     weight=0.2, armor_value=1, attack_value=0, durability=30, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000CA": Item("000000CA", "Whisperwind Bow", "A bow favored by skilled archers, known for its whisper-quiet string and deadly accuracy.",
                     weight=2.5, armor_value=0, attack_value=45, durability=70, rarity="Uncommon",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000CB": Item("000000CB", "Chaos Stone", "A stone infused with chaotic energy, unleashing unpredictable elemental effects upon activation.",
                     weight=0.3, armor_value=0, attack_value=0, durability=30, rarity="Rare",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000CC": Item("000000CC", "Enchanted Earrings", "Earrings adorned with enchantments, increasing the wearer's magical affinity and spellcasting proficiency.",
                     weight=0.2, armor_value=1, attack_value=0, durability=20, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000CD": Item("000000CD", "Soulbound Gauntlets", "Gauntlets imbued with the essence of powerful souls, increasing the wearer's strength and resilience.",
                     weight=1.0, armor_value=5, attack_value=0, durability=60, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000CE": Item("000000CE", "Stormcaller Ring", "A ring that harnesses the power of storms, allowing the wearer to summon lightning and control the weather.",
                     weight=0.1, armor_value=2, attack_value=0, durability=20, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage="Lightning", required_level=0, quest_item=False),
    "000000CF": Item("000000CF", "Glimmering Crown", "A crown adorned with glimmering jewels, representing nobility and granting enhanced magical presence.",
                     weight=0.5, armor_value=3, attack_value=0, durability=40, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D0": Item("000000D0", "Phantom Blade", "A blade that phases in and out of reality, allowing the wielder to bypass defenses and strike ethereal targets.",
                     weight=1.5, armor_value=0, attack_value=35, durability=60, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D1": Item("000000D1", "Voidstone Pendant", "A pendant containing a fragment of the void, providing increased resistance to dark magic.",
                     weight=0.2, armor_value=2, attack_value=0, durability=30, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D2": Item("000000D2", "Crescent Blade", "A curved blade resembling the moon's crescent, enhancing the wielder's agility and critical strike chance.",
                     weight=1.8, armor_value=0, attack_value=40, durability=70, rarity="Uncommon",
                     value=250, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D3": Item("000000D3", "Arcane Bracelet", "A bracelet infused with arcane energy, enhancing the wearer's spellcasting speed and mana regeneration.",
                     weight=0.3, armor_value=1, attack_value=0, durability=30, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D4": Item("000000D4", "Duskblade", "A blade forged from twilight steel, radiating with a haunting aura and increasing shadow-based attacks.",
                     weight=2.0, armor_value=0, attack_value=45, durability=70, rarity="Uncommon",
                     value=300, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D5": Item("000000D5", "Enchanted Chalice", "A chalice filled with magical energy, restoring the user's health and mana when consumed.",
                     weight=0.5, armor_value=0, attack_value=0, durability=40, rarity="Uncommon",
                     value=150, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D6": Item("000000D6", "Spectral Cloak", "A cloak woven from spectral threads, providing increased evasion and resistance against ethereal attacks.",
                     weight=1.5, armor_value=5, attack_value=0, durability=70, rarity="Uncommon",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D7": Item("000000D7", "Arcane Talisman", "A talisman infused with arcane magic, amplifying the wearer's spellcasting potency and accuracy.",
                     weight=0.2, armor_value=2, attack_value=0, durability=30, rarity="Uncommon",
                     value=120, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D8": Item("000000D8", "Luminous Earrings", "Earrings adorned with radiant gems, bestowing a radiant aura and increased magical power.",
                     weight=0.2, armor_value=1, attack_value=0, durability=20, rarity="Uncommon",
                     value=80, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000D9": Item("000000D9", "Venomous Vial", "A vial containing potent venom, coating weapons with deadly poison upon application.",
                     weight=0.1, armor_value=0, attack_value=0, durability=10, rarity="Uncommon",
                     value=80, usable=True, stackable=True, effects=None,
                     range=None, elemental_damage="Poison", required_level=0, quest_item=False),
    "000000DA": Item("000000DA", "Sage's Tome", "A tome filled with ancient wisdom and knowledge, increasing the wearer's intellect and spellcasting abilities.",
                     weight=1.5, armor_value=0, attack_value=0, durability=50, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000DB": Item("000000DB", "Crystal Shard", "A shard of enchanted crystal, radiating with residual magical energy.",
                     weight=0.1, armor_value=0, attack_value=0, durability=10, rarity="Common",
                     value=50, usable=False, stackable=True, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000DC": Item("000000DC", "Arcane Bracers", "Bracers infused with arcane power, increasing the wearer's spellcasting speed and accuracy.",
                     weight=0.4, armor_value=3, attack_value=0, durability=30, rarity="Uncommon",
                     value=150, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000DD": Item("000000DD", "Whispering Dagger", "A dagger that whispers secrets to the wielder, increasing critical strike chance and granting sneak attack bonuses.",
                     weight=0.5, armor_value=0, attack_value=30, durability=50, rarity="Uncommon",
                     value=200, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000DE": Item("000000DE", "Scepter of Shadows", "A scepter shrouded in darkness, channeling the power of shadows and granting control over the unseen.",
                     weight=2.0, armor_value=0, attack_value=40, durability=60, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000DF": Item("000000DF", "Crown of Illusions", "A crown that creates illusions and conceals the wearer's true identity, granting increased deception and stealth abilities.",
                     weight=0.8, armor_value=2, attack_value=0, durability=50, rarity="Rare",
                     value=400, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False),
    "000000E0": Item("000000E0", "Crystal of Tranquility", "A crystal that emits a calming aura, reducing stress and increasing focus.",
                     weight=0.2, armor_value=0, attack_value=0, durability=20, rarity="Uncommon",
                     value=100, usable=False, stackable=False, effects=None,
                     range=None, elemental_damage=None, required_level=0, quest_item=False)
}

