#location_definitions.py

from location_classes import Universe, Planet, Continent, Country, Region, State, Province, City, Village, Town, Landmark

# Create instances of locations

one_alpha = Universe("The Universe", "A vast cosmos")
thulea = Planet("Thulea", "A mysterious and enchanting planet in the far reaches of the universe.")
lumos = Continent("Lumos", "A continent rich in history and ancient ruins.")
dawnbreak = Region("Dawnbreak", "A region where the first rays of sunlight touch the land.")
luminaria = Country("Luminaria", "A country known for its radiant beauty and rich culture.")
astravale = State("Astravale", "A state nestled in the valley of astral wonders.")
province = Province("Ontario", "A province in Canada")
luminaria_city = Village("Luminaria City", "A bustling city that shines like a beacon of light.")
royal_library = Landmark("Royal Library", "A grand library that holds the knowledge of countless ages.")
luminaria_city.add_landmark(royal_library)
starcrest = Village("Starcrest", "A peaceful village known for its stargazing observatory.")
astral_archive = Landmark("Astral Archive", "An ancient repository of celestial knowledge.")
starcrest.add_landmark(astral_archive)
ezitahan = Country("Ezitahan", "A country of ancient traditions and mystical secrets.")
reqedor = State("Reqedor", "A state with lush landscapes and a deep connection to nature.")
wravora = Village("Wravora", "A charming village nestled in the heart of the wilderness.")
pekkopan_tower = Landmark("Pekkopan Tower", "A towering structure that houses the wisdom of the ancient Pekko tribe.")
wravora.add_landmark(pekkopan_tower)
ikrecrizar = Village("Ikrecrizar", "A remote village known for its skilled artisans and craftsmanship.")
erissenem_gardens = Landmark("Erissenem Gardens", "Exquisite gardens filled with rare and mystical plants.")
ikrecrizar.add_landmark(erissenem_gardens)
yocutha = Country("Yocutha", "A country shrouded in mystery and ancient legends.")
dawnshire = State("Dawnshire", "A state where the first light of dawn brings hope and new beginnings.")
shimmerfield = Village("Shimmerfield", "A village adorned with shimmering fields of luminescent flowers.")
trilith_drift_palace = Landmark("Trilith Drift Palace", "A magnificent palace perched on floating rock formations.")
shimmerfield.add_landmark(trilith_drift_palace)
argentia_reach = Village("Argentia Reach", "A coastal village renowned for its silvery beaches and sparkling waters.")
verdantide_glade = Landmark("Verdantide Glade", "An enchanting glade where nature flourishes in vibrant hues.")
argentia_reach.add_landmark(verdantide_glade)
frostholm_highlands = Region("Frostholm Highlands", "A region of icy landscapes and majestic snow-capped mountains.")
mugulux = Country("Mugulux", "A country known for its frozen tundras and resilient people.")
frostholm = State("Frostholm", "A state where frost and ice dominate the landscape.")
frostholm_village = Village("Frostholm Village", "A cozy village nestled amidst snowy valleys.")
hearthfire_inn = Landmark("Hearthfire Inn", "A warm and welcoming inn where travelers find respite from the cold.")
frostholm_village.add_landmark(hearthfire_inn)
astralyn_bluff = Village("Astralyn Bluff", "A village perched on a cliff overlooking vast astral plains.")
emberfall_enclave = Landmark("Emberfall Enclave", "A hidden sanctuary where embers dance and flicker eternally.")
astralyn_bluff.add_landmark(emberfall_enclave)
aine_pusea = Country("Ainepusea", "A country of mesmerizing landscapes and mystical energies.")
stormwatch_crest = State("Stormwatch Crest", "A state where stormy skies unleash raw elemental power.")
stormwatch_city = Village("Stormwatch City", "A bustling city where lightning crackles through the air.")
frostholm_highlands_citadel = Landmark("Frostholm Highlands Citadel", "An imposing fortress that stands as a beacon of strength.")
stormwatch_city.add_landmark(frostholm_highlands_citadel)
havenholm_vale = Village("Havenholm Vale", "A tranquil village nestled in a verdant valley.")
royal_citadel = Landmark("Royal Citadel", "The majestic seat of power where rulers govern with wisdom and grace.")
havenholm_vale.add_landmark(royal_citadel)
shadowfen_marsh = Region("Shadowfen Marsh", "A region cloaked in darkness and mystery, where shadows dance on murky waters.")
phakkeacaea = Country("Phakkeacaea", "A country of mist-laden forests and ancient arcane traditions.")
shadowfen_marsh_state = State("Shadowfen Marsh", "A state where the marshlands hold ancient secrets and hidden dangers.")
ezitahan_city = Village("Ezitahan", "A city where ancient and modern cultures converge.")
reqedor_village = Village("Reqedor", "A village known for its tranquil beauty and serene atmosphere.")
shadowfen_marsh_state.add_place(ezitahan_city)
shadowfen_marsh_state.add_place(reqedor_village)
zeloria_landmark = Landmark("Zeloria", "A mystical sanctuary hidden within the depths of Shadowfen Marsh.")
ezitahan_city.add_landmark(zeloria_landmark)
yocutha_village = Village("Yocutha", "A village brimming with rich folklore and ancient traditions.")
mugulux_landmark = Landmark("Mugulux", "A sacred site where the spirits of the ancestors are honored.")
yocutha_village.add_landmark(mugulux_landmark)
luxuinia = Country("Luxuinia", "A country known for its ethereal beauty and captivating aura.")
astralyn_bluff_state = State("Astralyn Bluff", "A state where the bluffs hold breathtaking views of astral phenomena.")
pekkopan_village = Village("Pekkopan", "A village renowned for its vibrant festivals and lively celebrations.")
ikrecrizar_village = Village("Ikrecrizar", "A village where creativity and artistic expression flourish.")
luxuinia_state = State("Astralyn Bluff", "A state where astral energies permeate every corner.")
pekkopan_village.add_landmark(zeloria_landmark)
ikrecrizar_village.add_landmark(zeloria_landmark)
astralyn_bluff_state.add_place(pekkopan_village)
astralyn_bluff_state.add_place(ikrecrizar_village)
aiharreolum = Continent("Aiharreolum", "A continent steeped in celestial mysteries and magic.")
uzaikaton = Region("Uzaikaton", "A region where ancient ruins and celestial phenomena intertwine.")
eaprastorith = Country("Eaprastorith", "A country where the power of the heavens is harnessed.")
havenholm_vale_state = State("Havenholm Vale", "A state blessed with bountiful nature and harmonious communities.")
astralyn_bluff_city = Village("Astralyn Bluff", "A city where the astral energies resonate in every step.")
stormwatch_crest_village = Village("Stormwatch Crest", "A village nestled amidst the storm-wracked peaks.")
havenholm_vale_state.add_place(astralyn_bluff_city)
havenholm_vale_state.add_place(stormwatch_crest_village)
stormwatch_crest_village.add_landmark(frostholm_highlands_citadel)
eaprastorith.add_place(havenholm_vale_state)
eaprastorith.add_place(stormwatch_crest_village)
astosheopan = Country("Astosheopan", "A country blessed with celestial wonders and mystical phenomena.")
celestria_expanse = State("Celestria Expanse", "A state where the celestial veil is thin, allowing glimpses of other realms.")
ezitahan_city = Village("Ezitahan", "A city where ancient and modern cultures converge.")
reqedor_village = Village("Reqedor", "A village known for its tranquil beauty and serene atmosphere.")
yocutha_village = Village("Yocutha", "A village brimming with rich folklore and ancient traditions.")
ezitahan_city.add_landmark(zeloria_landmark)
reqedor_village.add_landmark(zeloria_landmark)
yocutha_village.add_landmark(zeloria_landmark)
celestria_expanse.add_place(ezitahan_city)
celestria_expanse.add_place(reqedor_village)
celestria_expanse.add_place(yocutha_village)

toggurean = Region("Toggurean", "A region of rugged landscapes and untamed beauty.")
homaivaria = Country("Homaivaria", "A country known for its vast forests and deep spiritual connections.")
frostholm_highlands_state = State("Frostholm Highlands", "A state where towering peaks touch the skies and winter's grip never fades.")
havenholm_vale_state = State("Havenholm Vale", "A state blessed with bountiful nature and harmonious communities.")
astralyn_bluff_city = Village("Astralyn Bluff", "A city where the astral energies resonate in every step.")
shadowfen_marsh_city = Village("Shadowfen Marsh", "A city surrounded by mist-shrouded marshlands.")
frostholm_highlands_state.add_place(astralyn_bluff_city)
frostholm_highlands_state.add_place(shadowfen_marsh_city)
shadowfen_marsh_city.add_landmark(zeloria_landmark)
homaivaria.add_place(frostholm_highlands_state)
homaivaria.add_place(shadowfen_marsh_city)

hegrukya = Country("Hegruckya", "A country where ancient spirits and primal forces shape the land.")
stormwatch_crest_state = State("Stormwatch Crest", "A state where the storms rage with unrivaled fury.")
pekkopan_village = Village("Pekkopan", "A village renowned for its vibrant festivals and lively celebrations.")
ikrecrizar_village = Village("Ikrecrizar", "A village where creativity and artistic expression flourish.")
stormwatch_crest_state.add_place(pekkopan_village)
stormwatch_crest_state.add_place(ikrecrizar_village)
pekkopan_village.add_landmark(zeloria_landmark)
ikrecrizar_village.add_landmark(zeloria_landmark)
hegrukya.add_place(stormwatch_crest_state)
hegrukya.add_place(pekkopan_village)
hegrukya.add_place(ikrecrizar_village)

kreottodia = Region("Kreottodia", "A region of enchanting landscapes and ancient wonders.")
xuppagary = Country("Xuppagary", "A country known for its diverse terrains and cultural heritage.")
trilith_drift_state = State("Trilith Drift", "A state where floating rocks defy gravity and create breathtaking vistas.")
argentia_reach_city = Village("Argentia Reach", "A city embraced by the shimmering silver beaches.")
frostholm_city = Village("Frostholm", "A city surrounded by snow-capped mountains and frost-laden forests.")
trilith_drift_state.add_place(argentia_reach_city)
trilith_drift_state.add_place(frostholm_city)
argentia_reach_city.add_landmark(zeloria_landmark)
xuppagary.add_place(trilith_drift_state)
xuppagary.add_place(argentia_reach_city)

hisrasal = Country("Hisrasal", "A country where the dawn's first light holds divine significance.")
dawnshire_state = State("Dawnshire", "A state where the break of dawn marks the beginning of new possibilities.")
luminaria_city = Village("Luminaria City", "A city bathed in the golden glow of the rising sun.")
starcrest_village = Village("Starcrest", "A village known for its captivating stargazing experiences.")
luminaria_city.add_landmark(royal_library)
starcrest_village.add_landmark(astral_archive)
dawnshire_state.add_place(luminaria_city)
dawnshire_state.add_place(starcrest_village)
hisrasal.add_place(dawnshire_state)

mustopis = Continent("Mustopis", "A continent where magic and technology intertwine harmoniously.")
draisaborg = Region("Draisaborg", "A region known for its vibrant cities and cultural diversity.")
grufathage = Country("Grufathage", "A country of diverse landscapes and rich folklore.")
shimmerfield_state = State("Shimmerfield", "A state blessed with shimmering fields and enchanting vistas.")
ezitahan_city = Village("Ezitahan", "A city where ancient and modern cultures converge.")
reqedor_village = Village("Reqedor", "A village known for its tranquil beauty and serene atmosphere.")
yocutha_village = Village("Yocutha", "A village brimming with rich folklore and ancient traditions.")
ezitahan_city.add_landmark(zeloria_landmark)
reqedor_village.add_landmark(zeloria_landmark)
yocutha_village.add_landmark(zeloria_landmark)
shimmerfield_state.add_place(ezitahan_city)
shimmerfield_state.add_place(reqedor_village)
shimmerfield_state.add_place(yocutha_village)
grufathage.add_place(shimmerfield_state)
grufathage.add_place(ezitahan_city)
grufathage.add_place(reqedor_village)
grufathage.add_place(yocutha_village)
grufathage.add_place(zeloria_landmark)
grufathage.add_place(royal_library)
grufathage.add_place(astral_archive)
grufathage.add_place(trilith_drift_palace)
grufathage.add_place(verdantide_glade)

ouyecrogary = Region("Ouyecrogary", "A region where ancient ruins hold untold secrets and hidden treasures.")
hakusha = Country("Hakusha", "A country where the elements dance in harmony and spiritual enlightenment is sought.")
frostholm_highlands_state = State("Frostholm Highlands", "A state where towering peaks touch the skies and winter's grip never fades.")
havenholm_vale_state = State("Havenholm Vale", "A state blessed with bountiful nature and harmonious communities.")
astralyn_bluff_city = Village("Astralyn Bluff", "A city where the astral energies resonate in every step.")
shadowfen_marsh_city = Village("Shadowfen Marsh", "A city surrounded by mist-shrouded marshlands.")
frostholm_highlands_state.add_place(astralyn_bluff_city)
frostholm_highlands_state.add_place(shadowfen_marsh_city)
astralyn_bluff_city.add_landmark(zeloria_landmark)
hakusha.add_place(frostholm_highlands_state)
hakusha.add_place(astralyn_bluff_city)
hakusha.add_place(shadowfen_marsh_city)

astibberal = Country("Astibberal", "A country where ancient wisdom and arcane arts intertwine.")
oudrattuthia = Region("Oudrattuthia", "A region of dark forests and hidden magical enclaves.")
hegrukya_state = State("Hegruckya", "A state where ancient spirits and primal forces shape the land.")
stormwatch_crest_village = Village("Stormwatch Crest", "A village embraced by stormy skies and fierce winds.")
pekkopan_village = Village("Pekkopan", "A village renowned for its vibrant festivals and lively celebrations.")
zeloria_landmark = Landmark("Zeloria", "A place of ancient power and mystic energies.")
hegrukya_state.add_place(stormwatch_crest_village)
hegrukya_state.add_place(pekkopan_village)
stormwatch_crest_village.add_landmark(zeloria_landmark)
astibberal.add_place(hegrukya_state)
astibberal.add_place(stormwatch_crest_village)
oudrattuthia.add_place(pekkopan_village)
oudrattuthia.add_place(zeloria_landmark)
astibberal.add_place(oudrattuthia)

hegrukya.add_place(astibberal)

kreassiston = Region("Kreassiston", "A region of ancient ruins and magical anomalies.")
zenagon = Continent("Zenagon", "A continent where mysticism and technological advancements coexist.")
keasodor = Region("Keasodor", "A region known for its lush forests and harmonious coexistence with nature.")
kracceviel = Country("Kracceviel", "A country celebrated for its vibrant culture and rich traditions.")
trilith_drift_state = State("Trilith Drift", "A state where floating rocks defy gravity and create breathtaking vistas.")
argentia_reach_city = Village("Argentia Reach", "A city embraced by the shimmering silver beaches.")
frostholm_city = Village("Frostholm", "A city surrounded by snow-capped mountains and frost-laden forests.")
trilith_drift_state.add_place(argentia_reach_city)
trilith_drift_state.add_place(frostholm_city)
argentia_reach_city.add_landmark(zeloria_landmark)
kracceviel.add_place(trilith_drift_state)
kracceviel.add_place(argentia_reach_city)
kracceviel.add_place(zeloria_landmark)

thaslisan = Country("Thaslisan", "A country known for its captivating landscapes and ethereal beauty.")
dawnshire_state = State("Dawnshire", "A state where the break of dawn marks the beginning of new possibilities.")
luminaria_city = Village("Luminaria City", "A city bathed in the golden glow of the rising sun.")
starcrest_village = Village("Starcrest", "A village known for its captivating stargazing experiences.")
luminaria_city.add_landmark(royal_library)
starcrest_village.add_landmark(astral_archive)
dawnshire_state.add_place(luminaria_city)
dawnshire_state.add_place(starcrest_village)
thaslisan.add_place(dawnshire_state)

darrethen = Region("Darrethen", "A region where enchantment and elegance pervade every corner.")
celestia = Country("Celestia", "A country where celestial beauty and divine radiance shine brightly.")
shimmerfield_state = State("Shimmerfield", "A state blessed with shimmering fields and enchanting vistas.")
ezitahan_city = Village("Ezitahan", "A city where ancient and modern cultures converge.")
reqedor_village = Village("Reqedor", "A village known for its tranquil beauty and serene atmosphere.")
yocutha_village = Village("Yocutha", "A village brimming with rich folklore and ancient traditions.")
ezitahan_city.add_landmark(zeloria_landmark)
reqedor_village.add_landmark(zeloria_landmark)
yocutha_village.add_landmark(zeloria_landmark)
shimmerfield_state.add_place(ezitahan_city)
shimmerfield_state.add_place(reqedor_village)
shimmerfield_state.add_place(yocutha_village)
darrethen.add_place(shimmerfield_state)
darrethen.add_place(ezitahan_city)
darrethen.add_place(reqedor_village)
darrethen.add_place(yocutha_village)
celestia.add_place(darrethen)

sunspire = Country("Sunspire", "A country where the sun's radiant energy fuels life and inspiration.")
dawnshire_state = State("Dawnshire", "A state where the break of dawn marks the beginning of new possibilities.")
luminaria_city = Village("Luminaria City", "A city bathed in the golden glow of the rising sun.")
starcrest_village = Village("Starcrest", "A village known for its captivating stargazing experiences.")
luminaria_city.add_landmark(royal_library)
starcrest_village.add_landmark(astral_archive)
dawnshire_state.add_place(luminaria_city)
dawnshire_state.add_place(starcrest_village)
sunspire.add_place(dawnshire_state)

eclipsia = Continent("Eclipsia", "A continent where darkness and light dance in eternal balance.")
gloaming_province = Region("Gloaming Province", "A region bathed in the soft hues of twilight and shimmering stars.")
illumina = Country("Illumina", "A country known for its radiant landscapes and ethereal allure.")
astravale = State("Astravale", "A state nestled in the valley of astral wonders.")
luminaria_city = Village("Luminaria City", "A city bathed in the golden glow of the rising sun.")
starcrest_village = Village("Starcrest", "A village known for its captivating stargazing experiences.")
starcrest_village.add_landmark(astral_archive)
astravale.add_place(luminaria_city)
astravale.add_place(starcrest_village)
astravale.add_place(zeloria_landmark)
astravale.add_place(royal_library)
astravale.add_place(astral_archive)
astravale.add_place(trilith_drift_palace)
astravale.add_place(verdantide_glade)
illumina.add_place(astravale)
illumina.add_place(luminaria_city)
illumina.add_place(starcrest_village)
eventide = Country("Eventide", "A country where twilight casts a bewitching spell and shadows come alive.")
reqedor_state = State("Reqedor", "A state where ancient forests and mystical beings coexist in harmony.")
wravora_city = Village("Wravora", "A city embraced by the tranquility of nature.")
ikrecrizar_village = Village("Ikrecrizar", "A village where creativity and artistic expression flourish.")
wravora_city.add_landmark(pekkopan_tower)
ikrecrizar_village.add_landmark(erissenem_gardens)
reqedor_state.add_place(wravora_city)
reqedor_state.add_place(ikrecrizar_village)
eventide.add_place(reqedor_state)

lusteria = Region("Lusteria", "A region of shimmering landscapes and magical allure.")
dawnshire = Country("Dawnshire", "A country where the first light of dawn brings hope and new beginnings.")
dawnshire_state = State("Dawnshire", "A state where the break of dawn marks the beginning of new possibilities.")
shimmerfield_state = State("Shimmerfield", "A state blessed with shimmering fields and enchanting vistas.")
shimmerfield_city = Village("Shimmerfield", "A city adorned with shimmering fields of luminescent flowers.")
trilith_drift_palace = Landmark("Trilith Drift Palace", "A magnificent palace perched on floating rock formations.")
shimmerfield_city.add_landmark(trilith_drift_palace)
argentia_reach_city = Village("Argentia Reach", "A coastal village renowned for its silvery beaches and sparkling waters.")
verdantide_glade = Landmark("Verdantide Glade", "An enchanting glade where nature flourishes in vibrant hues.")
argentia_reach_city.add_landmark(verdantide_glade)
dawnshire_state.add_place(shimmerfield_city)
dawnshire_state.add_place(argentia_reach_city)
lusteria.add_place(dawnshire_state)

shadowfen_marsh = Region("Shadowfen Marsh", "A region cloaked in darkness and mystery, where shadows dance on murky waters.")
phakkeacaea = Country("Phakkeacaea", "A country of mist-laden forests and ancient arcane traditions.")
shadowfen_marsh_state = State("Shadowfen Marsh", "A state where the marshlands hold ancient secrets and hidden dangers.")
ezitahan_city = Village("Ezitahan", "A city where ancient and modern cultures converge.")
reqedor_village = Village("Reqedor", "A village known for its tranquil beauty and serene atmosphere.")
yocutha_village = Village("Yocutha", "A village brimming with rich folklore and ancient traditions.")
ezitahan_city.add_landmark(zeloria_landmark)
reqedor_village.add_landmark(zeloria_landmark)
yocutha_village.add_landmark(zeloria_landmark)
shadowfen_marsh_state.add_place(ezitahan_city)
shadowfen_marsh_state.add_place(reqedor_village)
shadowfen_marsh_state.add_place(yocutha_village)
shadowfen_marsh.add_place(shadowfen_marsh_state)

luxuinia = Country("Luxuinia", "A country known for its ethereal beauty and captivating aura.")
astralyn_bluff_state = State("Astralyn Bluff", "A state where the bluffs hold breathtaking views of astral phenomena.")
pekkopan_village = Village("Pekkopan", "A village renowned for its vibrant festivals and lively celebrations.")
ikrecrizar_village = Village("Ikrecrizar", "A village where creativity and artistic expression flourish.")
zeloria_landmark = Landmark("Zeloria", "A place of ancient power and mystic energies.")
luxuinia_state = State("Astralyn Bluff", "A state where astral energies permeate every corner.")
pekkopan_village.add_landmark(zeloria_landmark)
ikrecrizar_village.add_landmark(zeloria_landmark)
astralyn_bluff_state.add_place(pekkopan_village)
astralyn_bluff_state.add_place(ikrecrizar_village)
luxuinia.add_place(astralyn_bluff_state)

oudrattuthia = Region("Oudrattuthia", "A region of ancient forests and magical enclaves.")
hegrukya = Country("Hegruckya", "A country where ancient spirits and primal forces shape the land.")
frostholm_highlands_state = State("Frostholm Highlands", "A state where towering peaks touch the skies and winter's grip never fades.")
havenholm_vale_state = State("Havenholm Vale", "A state blessed with bountiful nature and harmonious communities.")
astralyn_bluff_city = Village("Astralyn Bluff", "A city where the astral energies resonate in every step.")
shadowfen_marsh_city = Village("Shadowfen Marsh", "A city surrounded by mist-shrouded marshlands.")
frostholm_highlands_state.add_place(astralyn_bluff_city)
frostholm_highlands_state.add_place(shadowfen_marsh_city)
astralyn_bluff_city.add_landmark(zeloria_landmark)
hegrukya.add_place(frostholm_highlands_state)
hegrukya.add_place(astralyn_bluff_city)
hegrukya.add_place(shadowfen_marsh_city)

kreassiston = Region("Kreassiston", "A region of ancient ruins and magical anomalies.")
kreassiston.add_place(zeloria_landmark)
kreassiston.add_place(royal_library)
kreassiston.add_place(astral_archive)
kreassiston.add_place(trilith_drift_palace)
kreassiston.add_place(verdantide_glade)

xuppagary = Country("Xuppagary", "A country known for its diverse terrains and cultural heritage.")
trilith_drift_state = State("Trilith Drift", "A state where floating rocks defy gravity and create breathtaking vistas.")
argentia_reach_city = Village("Argentia Reach", "A city embraced by the shimmering silver beaches.")
frostholm_city = Village("Frostholm", "A city surrounded by snow-capped mountains and frost-laden forests.")
trilith_drift_state.add_place(argentia_reach_city)
trilith_drift_state.add_place(frostholm_city)
argentia_reach_city.add_landmark(zeloria_landmark)
xuppagary.add_place(trilith_drift_state)
xuppagary.add_place(argentia_reach_city)

thaslisan = Country("Thaslisan", "A country known for its captivating landscapes and ethereal beauty.")
dawnshire_state = State("Dawnshire", "A state where the break of dawn marks the beginning of new possibilities.")
luminaria_city = Village("Luminaria City", "A city bathed in the golden glow of the rising sun.")
starcrest_village = Village("Starcrest", "A village known for its captivating stargazing experiences.")
luminaria_city.add_landmark(royal_library)
starcrest_village.add_landmark(astral_archive)
dawnshire_state.add_place(luminaria_city)
dawnshire_state.add_place(starcrest_village)
thaslisan.add_place(dawnshire_state)

darrethen = Region("Darrethen", "A region where enchantment and elegance pervade every corner.")
celestia = Country("Celestia", "A country where celestial beauty and divine radiance shine brightly.")
shimmerfield_state = State("Shimmerfield", "A state blessed with shimmering fields and enchanting vistas.")
ezitahan_city = Village("Ezitahan", "A city where ancient and modern cultures converge.")
reqedor_village = Village("Reqedor", "A village known for its tranquil beauty and serene atmosphere.")
yocutha_village = Village("Yocutha", "A village brimming with rich folklore and ancient traditions.")
ezitahan_city.add_landmark(zeloria_landmark)
reqedor_village.add_landmark(zeloria_landmark)
yocutha_village.add_landmark(zeloria_landmark)
shimmerfield_state.add_place(ezitahan_city)
shimmerfield_state.add_place(reqedor_village)
shimmerfield_state.add_place(yocutha_village)
darrethen.add_place(shimmerfield_state)
darrethen.add_place(ezitahan_city)
darrethen.add_place(reqedor_village)
darrethen.add_place(yocutha_village)
celestia.add_place(darrethen)

sunspire = Country("Sunspire", "A country where the sun's radiant energy fuels life and inspiration.")
dawnshire_state = State("Dawnshire", "A state where the break of dawn marks the beginning of new possibilities.")
luminaria_city = Village("Luminaria City", "A city bathed in the golden glow of the rising sun.")
starcrest_village = Village("Starcrest", "A village known for its captivating stargazing experiences.")
luminaria_city.add_landmark(royal_library)
starcrest_village.add_landmark(astral_archive)
dawnshire_state.add_place(luminaria_city)
dawnshire_state.add_place(starcrest_village)
sunspire.add_place(dawnshire_state)

universe = Universe("The Vast Cosmos", "A mysterious and expansive cosmos")
thelea = Planet("Thelea", "A mesmerizing celestial body brimming with otherworldly wonders")
continent = Continent("Zephyrion", "A continent within the realm of Thelea, where mystical landscapes and ancient civilizations intertwine")
country = Country("Etherea", "A mystical realm within the continent of Zephyrion, where magic and enchantment flourish")
region = Region("Azure Highlands", "A realm of breathtaking beauty and ethereal landscapes within the country of Etherea")
state = State("Astralweave", "A realm within the Azure Highlands, where cosmic energies intertwine with the fabric of reality")
province = Province("Luminary Reach", "An enchanting province in the realm of Astralweave, known for its radiant beauty and celestial wonders")
city = City("Stellaris", "The celestial capital city of the province Luminary Reach, where starlight dances upon ancient spires")
village = Village("Moonshadow", "A tranquil village nestled beneath the luminescent glow of celestial moons")
town = Town("Stardust Crossing", "A vibrant town where interstellar travelers gather and cosmic energies converge")
landmark = Landmark("Celestial Cascade", "A magnificent waterfall of shimmering stardust, flowing through the heart of the Astralweave realm")

# Add locations to containers

universe.add_location(thelea)
thelea.add_location(continent)
continent.add_location(country)
country.add_location(region)
region.add_location(state)
state.add_location(city)
state.add_location(village)
state.add_location(town)
country.add_location(province)
province.add_location(city)
province.add_location(town)
state.add_location(landmark)


